### ISSUE TITLE
对您对”2.11.数组Array“的介绍的建议

### ISSUE THREAD

**Issue by rinevard** [Reimenn/MyGDSciprtBook#13]
godot中的Array可以包含多种数据类型，我感觉可以考虑加入一个这样的例子。比如var array1 = [3, "Four"]。

**Comment by Reimenn** [comment]
感谢建议，已经添加在数组这一章节添加 "元素的类型" 小节

**Comment by rinevard** [comment]
Done

**Comment by rinevard** [comment]
很好的教程👍🏻爱来自中国

发送自 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
