### ISSUE TITLE
"2.12.遍历"一章中的range介绍似乎有误

### ISSUE THREAD

**Issue by rinevard** [Reimenn/MyGDSciprtBook#14]
您的原文是”range 这个方法会根据括号里的数字产生一个数组，里面分别是 1、2、3、4...直到括号里的数字，但不包括那个数。“
但数组是从0开始的。
![pic1](https://github.com/Reimenn/MyGDSciprtBook/assets/136295900/4258d60e-e1e2-45c3-ae9e-2b1baa92652d)

**Comment by Reimenn** [comment]
感谢指出，已经修改！

**Comment by rinevard** [comment]
Done
