### ISSUE TITLE
一处小错误

### ISSUE THREAD

**Issue by QuinnHu-star** [Reimenn/MyGDSciprtBook#17]
大佬你好，我正在看 GDScript 零基础图文入门，在 2.3 节：表达式与运算符中发现一处错误，如图所示：
![01B)GKUD8TF%3TS%E(QXSF9](https://github.com/Reimenn/MyGDSciprtBook/assets/118532590/37a46eb4-f99c-41bb-9b9a-b7b94198b07e)

**Comment by Reimenn** [comment]
感谢指正，我会尽快修改！

**Comment by Reimenn** [comment]
已解决
