### ISSUE TITLE
2.12遍历建议增加关于“物品的描述”

### ISSUE THREAD

**Issue by bbrazzaville** [Reimenn/MyGDSciprtBook#18]
var 背包 = ["水瓶", "钥匙", "金币"]
print("背包中有：")
for 物品 in 背包:
    print(物品)

其中“物品”是个临时变量，不需要提前声明，我也是问了copilot才知道的，刚看到的时候困扰了我好一会，不知道物品从何而来！
建议增加对“物品”的解释！感恩加油！

**Comment by Reimenn** [comment]
感谢反馈，我这就改
