### ISSUE TITLE
是否可以将一些专有名词和godot官方文档相统一以及是否可以为某一base创建其本身不存在的function

### ISSUE THREAD

**Issue by 123ysys** [Reimenn/MyGDSciprtBook#20]
建议：我看教程把function称作方法，而官方文档是把function称作函数，把method称作方法。不知道作者是否愿意将这些名称统一一下，或者在页面上用中英文同时指明一下，方便读者对照。

问题：我之所以提出这个建议，是我遇到了一个问题。我希望在TextRect节点中使用"get_pixel"，却得到这样的错误提示：
```
Invalid call. Nonexistent function 'get_pixel' in base 'TextureRect'.
```
从这里可以看到，似乎godot把节点TextureRect当作base，把get_pixel当作function。我想请问base和class（类）是一样的吗？以及function和method是一样的吗？如果不一样，那么哪个名词才是“方法”的意思？像这种希望在一个没有这种function的base中创建该function，应该怎么做？谢谢。

**Comment by Reimenn** [comment]
1. function 一般翻译成“函数”或“过程”，method 一般翻译成方法，但在绝大多数编程语言中，他们都没有区别。英文环境我不清楚，但中文环境下，在面向对象中使用 “方法” 这个名字更多一些。

> Godot 在代码中使用 func 声明方法，但是文档里一直在用 Method 指代这些 func，应该是为了迎合编程语言的传统吧，比如 javascript 就用 function 声明方法。

2. 那一条报错信息中的 base 指的是 base class，翻译过来是“基类”，所以本质上就是 class。“基类”这个名字对应教程中的“父类”。有人习惯将拥有继承关系的类称为“基类”和“派生类”，也有人习惯称为“父类”和“子类”。

> Godot 提供的很多内置“类”不一定是 GDScript 中定义的那种 class，有可能是底层 C++ 写的，我猜是因为这个他才用 “base” 代替 “class” 吧。

**Comment by Reimenn** [comment]
> Invalid call. Nonexistent function 'get_pixel' in base 'TextureRect'.

可以直接理解成

> 不正确的调用。基类 TextureRect 中不存在 get_pixel 方法。

**Comment by Reimenn** [comment]
关于最后一句 `在一个没有这种function的base中创建该function`，这在 GDScript 中做不到，我查文档看到 get_pixel 是 Image 类的方法，你应该看看文档怎么使用 image 类。
