### ISSUE TITLE
又来麻烦大佬了，关于类与继承该类的子类。

### ISSUE THREAD

**Issue by 123ysys** [Reimenn/MyGDSciprtBook#22]
又来麻烦大佬了。最近在做游戏原型时遇到了这么一个问题，我从Resource类中扩展了一个自定义的Skill类：
```
extend Resource
class_name Skill
#技能的名字
var name: String
#技能的所有者
var owner
#技能的描述
var description:

func _custom_function:
```
然后我又从这个Skill类中扩展了一些子类如BossSkill、PlayerSkill、SupporterSkill，现在我希望覆写这些子类中的属性与方法，如BossSkill中把name、owner和description改成独一无二的。但是我无法再在BossSkill中再次声明这些变量了，因为它们已在父类被声明过了。我该怎么做呢？

**Comment by Reimenn** [comment]
## 常规解决办法有两个：


**方法一**：直接给变量赋值，在子类的 `_ready` 方法或者 `_init` 方法中给这些变量赋值，然后保证其他地方不会修改这些值就行了。

**方法二**：为这些变量指定 getter 方法，并在子类中重写这些 gatter 方法。例如：

```gdscript
extends Resource
class_name Skill

var SkillName : String : get = get_skill_name

func get_skill_name():
	return "默认技能"
```

然后在子类中重写 `get_skill_name `就可以了

```gdscript
extends Skill
class_name NBSkill
	
func get_skill_name():
	return "NB 的技能"
```

---

一般来讲推荐方法二，但是方法一确实写起来简单，可以试试选一个自己喜欢的。

getter 方法这个名字教程里没提到，其实就是封装那一节讲的东西
