### ISSUE TITLE
多态章节有一些疑问

### ISSUE THREAD

**Issue by ggbond5277** [Reimenn/MyGDSciprtBook#27]
您好，在网上看到了您的教程，很有帮助

在多态章节有如下代码
```
var 某人的手机:手机 = 能发短信的手机.new()

某人的手机.打电话("10086")   
# 虽然 某人的手机 是手机类型，但其值是 能发短信的手机，所以调用的是 能发短信的手机 的打电话方法。

# 某人的手机.发短信("10086","Hello")
# 上面这句注释掉的代码是错误的。
# 虽然`能发短信的手机`能发短信，但是 某人的手机 是老手机类型，不包含发短信方法。
```

对于上面的说明不是很理解，`某人的手机`是从`能发短信的手机`实例化而来的，为什么不包含`发短信`方法呢？

打扰了 还望解答 谢谢

**Comment by Reimenn** [comment]
某个变量中存放的实例包含什么方法，通常都以变量的类型为准，不论其中装的是什么值。

注意第一行，`某人的手机`这个变量由`:手机`标记为了“手机”类型，结合前几章，“手机”这个类型是不包含发短信方法的。

这个例子中的这个手机实例确实能够发短信，只不过我们把他放入了`手机`类型的变量中，所以`某人的手机.发短信`会被编辑器提示错误。

**Comment by ggbond5277** [comment]
原来如此 谢谢
