### ISSUE TITLE
关于邀请其他大佬参与编写的可能性

### ISSUE THREAD

**Issue by saierXP** [Reimenn/MyGDSciprtBook#4]
作者大大，要不建个Q群或者国外平台也行（群里的大佬都有梯子），我可以去几个 godot 群里宣传一下，看能不能邀请大佬们加入，毕竟大佬也一直在群里回答问题，都是比较热情的。
但这几年了，说实话大佬们都没怎么总结新人遇到的问题，新人遇到同样的问题，大佬们也只能一遍遍的回答。我感觉主要是缺个人带头，没有编写问题合计之类的，虽然有一个官方文档，但还是有很多新手会遇到问题，毕竟大多都喜欢看视频，但视频要么外国的要么讲解不到位，总会出问题。
就gdscript来说，确实会有零基础的人在使用时看不懂报错（毕竟又是英文），官方文档又是一个大章节，查漏补缺还是比较麻烦。
文档还是比较适合共同贡献。
作者大大有加godot的Q群吗，很长时间基本上搜不到godot相关的群。

**Comment by Reimenn** [comment]
我就加了一两个q群，而且一直潜水，没什么熟人。

你愿意帮忙宣传的话当然可以
