### ISSUE TITLE
导出这一节可以加上其他常用export注解以及如何找到其他注解

### ISSUE THREAD

**Issue by saierXP** [Reimenn/MyGDSciprtBook#6]
按F1搜索`export`前缀可以找到全部的导出注解，跟在这些导出注解后面的是其他类型注解如`onready，icon，tool`等。
`export_range`对导出的数字进行范围限制或者浮点数步长。
`export_file`和`export_dir`对项目内文件获取路径。
其他实用注解有`export_category、export_group，export_subgroup`配合对导出属性分组、提供折叠。
这些注解内部文档给了例子，可以提一下有这些，然后让用户自己学习。
`export_group`这些可能需要一个直观的展示。
![image](https://user-images.githubusercontent.com/45038185/223692609-76c6c40d-b442-4fdd-abf7-d87d302b71cc.png)

**Comment by Reimenn** [comment]
等基础语法这些东西写完，再写一个扩展进阶篇，到时再介绍这些东西。

因为我考虑到，新人面对大量的新知识时，可能无法判断哪些是重点，一股脑写太多东西会增加新人入门的学习量，目前的主要目标还是让新人顺利入门。
