### ISSUE TITLE
玩家移动的代码错误

### ISSUE THREAD

**Issue by jihe520** [Reimenn/MyGDSciprtBook#7]
在整活移动，move_and_collide的方法实现在KinematicBody2D下，而你写的移动节点是extends RigidBody2D，没有move_and_collide，是不是错了

**Comment by jihe520** [comment]
在整活fire章节中，射击相关的逻辑中的ready（）,打成read（），小错误

**Comment by Reimenn** [comment]
根据 4.0 版本的引擎内置文档，可以找到 `move_and_collide` 方法定义在 PhysicBody2D 节点中，RigidBody2D 作为子类也可以使用这个方法。

下面的 ready 方法名马上修改，感谢指出错误。🙏
